### ISSUE TITLE
problem in `.username` method?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/repo-utils#1]
continue from https://github.com/verbose/verb-readme-generator/issues/4

Rethinking it.. for me make more sense to try to get `.gitUserName` first if there's not `author.username` instead of getting the `repository` owner? Meaning this:
- try to get `author.username`
- try to get `author.url`, parse it and get `owner`
- try to get `gitUserName()`
- finally, try to get `repository` or `homepage`, parse it and get `owner`

What you think?

**Comment by tunnckoCore** [comment]
Change would be this

``` js
repo.authorUsername = function(config, options) {
  var author = repo.author(config, options);
  if (utils.isObject(author)) {
    return author.username;
  }
};

repo.username = function(config, options) {
  if (!utils.isObject(config)) {
    throw new TypeError('expected an object');
  }

  var username = repo.authorUsername(config) || null;

  if (!utils.isString(username)) {
    var authorUrl = repo.authorUrl(config, options);
    if (/github\.com/.test(authorUrl)) {
      var parsed = utils.parseGithubUrl(authorUrl);
      username = parsed && parsed.owner || null;
    }
  }
  if (!utils.isString(username)) {
    username = repo.gitUserName(options);
  }
  if (!utils.isString(username)) {
    var str = config.repository || config.homepage;
    var parsed = utils.parseGithubUrl(str);
    username = parsed && parsed.owner || null;
  }

  return username;
};
```

in bonus, exposing `.authorUsername` method. Current bug is that in `.username` [it checks for `config.username` instead of `config.author.username` on line 509](https://github.com/jonschlinkert/repo-utils/blob/master/index.js#L509)

**Comment by jonschlinkert** [comment]
> make more sense to try to get .gitUserName first if there's not author.username instead of getting the repository owner

yeah I think you're right. Want to do a pr?

**Comment by tunnckoCore** [comment]
> Want to do a pr?

yea, i've done it locally, i'll do.
